### ISSUE TITLE
Build for Windows

### ISSUE THREAD

**Issue by baseoleph** [tontechio/pow-miner-gpu#107]
How to build pow-miner-gpu for windows? 

I want to build app by myself

**Comment by optimis3232** [comment]
look this file win64-pm-pmcuda-lc-compile.yml 
its help you (  its not very easy for new programmers )

**Comment by tontechio** [comment]
Please follow github build workflows:
https://github.com/tontechio/pow-miner-gpu/blob/main/.github/workflows/win64-pm-pmcuda-lc-compile.yml
https://github.com/tontechio/pow-miner-gpu/blob/main/.github/workflows/win64-pm-pmopencl-lc-compile.yml
