### ISSUE TITLE
processes of synchronization & completion

### ISSUE THREAD

**Issue by aavvaavv** [tontechio/pow-miner-gpu#108]
I have the same problem:
- I do not see the processes of synchronization;
- I do not see the completion;
- I do not see the marked option on the screen;
Is it OK?
Thanks;
![Screenshot_9](https://user-images.githubusercontent.com/36741121/144322978-d603603d-02f3-42d7-99f2-3862021eb37c.png)

**Comment by optimis3232** [comment]
its OK,  you need ~23 days for get 100 tons with this speed..  lol

**Comment by aavvaavv** [comment]
> its OK, you need ~23 days for get 100 tons with this speed.. lol
The total speed of 2x rigs = +- 50k Mhash/s
![Screenshot_9](https://user-images.githubusercontent.com/36741121/144352475-714b87b3-f92a-4056-8392-994fa06e5ffb.png)

**Comment by optimis3232** [comment]
Contact me with TG, you Russian ?  Ye its much faster with 2x rigs

**Comment by aavvaavv** [comment]
> Contact me with TG, you Russian ? Ye its much faster with 2x rigs

Your TG is?

**Comment by optimis3232** [comment]
В анкете указано всё

**Comment by optimis3232** [comment]
test sms

**Comment by tontechio** [comment]
The string about "master" is just a setting a value.
I can't any other problems here.

PS: contact random people via TG isn't a good idea ;-)

**Comment by aavvaavv** [comment]
> The string about "master" is just a setting a value. I can't any other problems here.
> 
> PS: contact random people via TG isn't a good idea ;-)

Thank you. You are right about the contact of the scammers.
Just want to be double sure, that processes of synchronization don't shown in the last versions;
Thank you;
