### ISSUE TITLE
Whats is "bounceable" addresses and  "non-bounceable" ?

### ISSUE THREAD

**Issue by optimis3232** [tontechio/pow-miner-gpu#114]
B) "User-friendly", which is obtained by first generating:
- one tag byte (0x11 for "bounceable" addresses, 0x51 for "non-bounceable"; add +0x80 if the address should not be accepted by software running in the production network)

bool bounceable{true};  // addresses must be bounceable by default

**Comment by tontechio** [comment]
not related to the miner

**Comment by optimis3232** [comment]
thx for help bro

**Comment by optimis3232** [comment]
#pragma pack(push, 1)
struct HData {
  unsigned char op[4];
  signed char flags = -4;                                                     <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< It is miner code <<<<<<<
  unsigned char expire[4] = {}, myaddr[32] = {}, rdata1[32] = {}, pseed[16] = {}, rdata2[32] = {};
  void inc() {
    for (long i = 31; !(rdata1[i] = ++(rdata2[i])); --i) {
    }
  }
  void set_expire(unsigned x) {
    for (int i = 3; i >= 0; --i) {
      expire[i] = (x & 0xff);
      x >>= 8;
    }
  }

  td::Slice as_slice() const {
    return td::Slice(reinterpret_cast<const td::uint8*>(this), sizeof(*this));
  }
};
