### ISSUE TITLE
tonlib-cuda-cli: Doesn't take into account BOOST_FACTOR (while pow-miner does)

### ISSUE THREAD

**Issue by garfae** [tontechio/pow-miner-gpu#116]
Release: 20211130.1

**When running tonlib-cuda-cli, BOOST FACTOR is properly identified but doesn't have an influence on actual runs.**

To reproduce:

- run tonlib-cuda-cli with BOOST FACTOR 4096 -> average speed is X:
![image](https://user-images.githubusercontent.com/18556195/145286335-d58b9ca1-3d29-40c5-b9fc-ba04dbbb3eed.png)

- run tonlib-cuda-cli with BOOST FACTOR 16384 -> average speed is still X:
![image](https://user-images.githubusercontent.com/18556195/145286577-77353ece-0fb0-49b3-8268-d96765746ac4.png)

This wouldn't matter in itself, except that tests done with pow-miner (using test-cuda.bat) give an optimal hashrate of 1300MH/s instead of 800MH/s currently obtained with tonlib-cuda-cli wrapper:

![image](https://user-images.githubusercontent.com/18556195/145285373-6cc324af-f7f2-477b-a498-4d238b81b681.png)

```
[ 2][t 0][2021-12-08 20:59:11.8649051][credits.cu:29]   [ START MINER, GPU ID: 0, boost factor: 4096, throughput: 2147483648 ]
[ 3][t 0][2021-12-08 20:59:16.8662826][Miner.cpp:105]   [ mining in progress, passed: 5001.5ms, hashes computed: 2147483648, instant speed: 607.442 Mhash/s, average speed: 429.364 Mhash/s ]
[ 3][t 0][2021-12-08 20:59:21.8714775][Miner.cpp:105]   [ mining in progress, passed: 10.0s, hashes computed: 4294967296, instant speed: 611.543 Mhash/s, average speed: 429.184 Mhash/s ]
[ 3][t 0][2021-12-08 20:59:22.7659709][Miner.cpp:105]   [ done, passed: 10.9s, hashes computed: 12884901888, instant speed: 626.567 Mhash/s, average speed: 1181.906 Mhash/s ]
[ 2][t 0][2021-12-08 20:59:22.7716516][credits.cu:29]   [ START MINER, GPU ID: 0, boost factor: 8192, throughput: 4294967296 ]
[ 3][t 0][2021-12-08 20:59:27.7731352][Miner.cpp:105]   [ mining in progress, passed: 5001.6ms, hashes computed: 0, instant speed: 1253.133 Mhash/s, average speed: 0.000 Mhash/s ]
[ 3][t 0][2021-12-08 20:59:32.7785371][Miner.cpp:105]   [ mining in progress, passed: 10.0s, hashes computed: 4294967296, instant speed: 663.750 Mhash/s, average speed: 429.170 Mhash/s ]
[ 3][t 0][2021-12-08 20:59:36.2314351][Miner.cpp:105]   [ done, passed: 13.5s, hashes computed: 17179869184, instant speed: 653.211 Mhash/s, average speed: 1276.316 Mhash/s ]
[ 2][t 0][2021-12-08 20:59:36.2376651][credits.cu:29]   [ START MINER, GPU ID: 0, boost factor: 16384, throughput: 8589934592 ]
[ 3][t 0][2021-12-08 20:59:41.2392227][Miner.cpp:105]   [ mining in progress, passed: 5001.9ms, hashes computed: 0, instant speed: 1306.422 Mhash/s, average speed: 0.000 Mhash/s ]
[ 3][t 0][2021-12-08 20:59:46.2443186][Miner.cpp:105]   [ mining in progress, passed: 10.0s, hashes computed: 0, instant speed: 1306.422 Mhash/s, average speed: 0.000 Mhash/s ]
[ 3][t 0][2021-12-08 20:59:48.9089331][Miner.cpp:105]   [ done, passed: 12.7s, hashes computed: 17179869184, instant speed: 689.436 Mhash/s, average speed: 1355.715 Mhash/s ]
[ 1][t 0][2021-12-08 20:59:48.9139067][pow-miner.cpp:226]
[ 1][t 0][2021-12-08 20:59:48.9146965][pow-miner.cpp:227]       *************************************************
[ 1][t 0][2021-12-08 20:59:48.9154664][pow-miner.cpp:228]       ***
[ 1][t 0][2021-12-08 20:59:48.9161837][pow-miner.cpp:229]       ***   best boost factor: 16384
[ 1][t 0][2021-12-08 20:59:48.9171338][pow-miner.cpp:230]       ***   best speed:        1355.715 Mhash/s
[ 1][t 0][2021-12-08 20:59:48.9178828][pow-miner.cpp:231]       ***
[ 1][t 0][2021-12-08 20:59:48.9186042][pow-miner.cpp:232]       *************************************************
[ 1][t 0][2021-12-08 20:59:48.9193054][pow-miner.cpp:233]
```

The 1300MH/s rate is also confirmed with pool mining using Danila miner.

**Comment by tontechio** [comment]
Benchmark run simplified task just to test your GPU, it's not a real job from a giver contract.

**Comment by garfae** [comment]
> Benchmark run simplified task just to test your GPU, it's not a real job from a giver contract.

Thank you for your input. However, some questions still remain. For instance, how do you explain:
- that changing BOOST FACTOR doesn't have any significant impact on hashrate (we tried with 1 and with 16384 and the results were similar)?
- that pool miners report around 1300MH/s on the same hardware?

Any assistance is appreciated!

**Comment by tontechio** [comment]
- boost factor impact. You should not expect huge impact because BF is a way to tune GPU a little bit, it's not an overclocking
- miner performance. It's not a secret that pow-miner not optimized and optimization is on the way. Another fact - miners hashrate output is not a measuring system, it's just a some readings just to be sure that everything works. A little difference in a hashrate sampling rate inside a miner will produce different results.
