### ISSUE TITLE
Why we spam Givers every 5 seconds ?

### ISSUE THREAD

**Issue by optimis3232** [tontechio/pow-miner-gpu#117]
https://github.com/tontechio/pow-miner-gpu/blob/main/tonlib/tonlib/tonlib-cli.cpp#652

can we change this value ?
static constexpr double QUERY_EACH = 5.0;

Нашел твой коммент 18 дней назад
Расширять канал. Майнер каждые 5 сек проверяет гивер на предмет актуальности текущий задачи.

Значит 5 секунд на каждую задачу майнер считает зря.
А это реально плохо.
Возможно ли установить соединение с гивером?

**Comment by tontechio** [comment]
Don't hesitate to change it in your own builds, it's an open source under GPLv2
