### ISSUE TITLE
Почему овнер такой упоротый и не хочет взаимодействия?

### ISSUE THREAD

**Issue by optimis3232** [tontechio/pow-miner-gpu#119]
Я впервые вижу твой код и улучшил его в 2 раза.
Может ты проявишь хоть капельку уважения ко мне?
Понимаешь что ТЫ мне не нужен, нужен тебе Я.
Короче, с Наступающим тебя

**Comment by tontechio** [comment]
Please be polite.
I've double checked pull-requests and didn't find any signs of your contribution. Please point me to your sources if I've missed something.

**Comment by optimis3232** [comment]
you say that you answered zero of my 20 questions ?

**Comment by tontechio** [comment]
Every single question has been answered, but it looks what you can't afford answers and expect something else. For example you'd mentioned some source additions and modification without any commits and/or pull-requests. I would like to suggest you act in a positive way and start contributing. Code is language, peace 🤘
