### ISSUE TITLE
Win10

### ISSUE THREAD

**Issue by optimis3232** [tontechio/pow-miner-gpu#120]
Уважаемый овнер проекта, так как ты дал 0 ответов на мои 20 вопросов, то я даже не надеюсь на твой адекватный комментарий, но я все равно попытаюсь задать вопрос.
Внимание ВОПРОС:
Как скомпилировать(по шагам) под Windows 10  это чудо, так чтоб не заняло у меня это 2 дня
PS:  дай мне контакт твоего босса

**Comment by tontechio** [comment]
I'm afraid it's impossible to continue conversation with you. You've passed some red line and ignored all given answers. I wish you luck and be polite.
