### ISSUE TITLE
[ GPU #0: bitcredit_setBlockTarget the provided PTX was compiled with an unsupported toolchain. ]

### ISSUE THREAD

**Issue by listyque** [tontechio/pow-miner-gpu#18]
Getting error after running this miner:
HW: GTX 1080 ti, stock clocks
461.40 Drivers

Run command:
:a
tonlib-cuda-cli.exe -v 3 -C global.config.json -e "pminer start kf-kkdY_B7p-77TLn2hUhM6QidWrrsl8FYWCIvBMpZKprBtN EQCMeBwVHiuoYtly0kFSVlr9hhbgJow3so82PvU1Yi9kHJsy 0 32"
goto a

**Comment by nickyharpor** [comment]
I have the same problem. My nVidia Driver is 470.05 (the unlocked mining driver). Does updating CUDA from 11.3 to 11.5 help?
