### ISSUE TITLE
Win7_x64 sendfile throws an error and an exception

### ISSUE THREAD

**Issue by dimwap** [tontechio/pow-miner-gpu#19]
Unhandled Exception [5568] tonlib-cuda-cli.exe
Last release of Windows tonlib-cuda-cli.exe crashes after syncronization while sending the found solution. Lite-client.exe crashing  while command "sendfile mined.boc".  pow-miner-cuda.exe working well. All this is only for Windows 7 64, I did not check the other.

**Comment by dimwap** [comment]
- System 
  - Provider 
   [ Name]  Application Error 
   - EventID 1005 
   [ Qualifiers]  49152 
    Level 2 
   Task 100 
    Keywords 0x80000000000000 
  - TimeCreated 
   [ SystemTime]  2021-10-31T20:38:33.000000000Z 
   EventRecordID 510927 
    Channel Application 
    Computer userpc 
   Security 
- EventData 
   tonlib-cuda-cli.exe 
   00000000 
   0

**Comment by dimwap** [comment]
Exception code: 0xc000001d
Error offset: 0x000000000023af01

**Comment by tontechio** [comment]
Looks like we need a dedicated build for system like yours

**Comment by DelphiR** [comment]
Yes. We shoud try to issue the older build release for system like win 7 x64. 
Let's wait some time, we are in process to attempt to do that

**Comment by DelphiR** [comment]
Hi. I attached the dedicated build for test the possbile correct of this problem
Download it [minertools-cuda-windows-x86-64-winsrv16-cuda-10-2.zip](https://github.com/tontechio/pow-miner-gpu/files/7484250/minertools-cuda-windows-x86-64-winsrv16-cuda-10-2.zip)
: 
And return here the feedback with result

**Comment by DelphiR** [comment]
Replace your current miner files with the files from archive and start anything again

**Comment by dimwap** [comment]
the same

**Comment by dimwap** [comment]
Контейнер ошибки 90570244, тип 502405275
Имя события: APPCRASH
Ответ: Нет данных
Идентификатор CAB: 0

Сигнатура проблемы:
P1: tonlib-cuda-cli.exe
P2: 0.0.0.0
P3: 6182e60e
P4: tonlib-cuda-cli.exe
P5: 0.0.0.0
P6: 6182e60e
P7: c000001d
P8: 000000000021b621
P9: 
P10:

**Comment by DelphiR** [comment]
ok, Please make the new identical attempt with the next ones:
[minertools-opencl-windows-x86-64-winsrv16-cuda-10-1.zip](https://github.com/tontechio/pow-miner-gpu/files/7487023/minertools-opencl-windows-x86-64-winsrv16-cuda-10-1.zip)
[minertools-cuda-windows-x86-64-winsrv16-cuda-10-1.zip](https://github.com/tontechio/pow-miner-gpu/files/7487026/minertools-cuda-windows-x86-64-winsrv16-cuda-10-1.zip)

**Comment by DelphiR** [comment]
And also compare with opencl version
