### ISSUE TITLE
AMD windows 10 error

### ISSUE THREAD

**Issue by nightly058** [tontechio/pow-miner-gpu#20]
Microsoft Windows version 1809
AMD driver 21.10.2

Error

Имя сбойного приложения: tonlib-opencl-cli.exe, версия: 0.0.0.0, метка времени: 0x617add66
Имя сбойного модуля: tonlib-opencl-cli.exe, версия: 0.0.0.0, метка времени: 0x617add66
Код исключения: 0xc000001d
Смещение ошибки: 0x00000000002292a1
Идентификатор сбойного процесса: 0x1558
Время запуска сбойного приложения: 0x01d7cf7d8bda3be4
Путь сбойного приложения: C:\Users\user\Downloads\minertools-opencl-windows-x86-64 (1)\deploy_dir\tonlib-opencl-cli.exe
Путь сбойного модуля: C:\Users\user\Downloads\minertools-opencl-windows-x86-64 (1)\deploy_dir\tonlib-opencl-cli.exe
Идентификатор отчета: 953d5260-b935-4190-9c22-dec145492aea
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:

**Comment by nightly058** [comment]
![image_2021-11-01_20-12-02](https://user-images.githubusercontent.com/79964068/139760100-f0ce8deb-91ec-47f8-868f-ff0cc129ab82.png)

**Comment by DelphiR** [comment]
I attached the dedicated build 
Download and test it:
[minertools-opencl-windows-x86-64-winsrv16.zip](https://github.com/tontechio/pow-miner-gpu/files/7484255/minertools-opencl-windows-x86-64-winsrv16.zip)
Return the feedback of  result here
