### ISSUE TITLE
Can't run pow-miner-opencl on all available GPUs.

### ISSUE THREAD

**Issue by Suhar777777** [tontechio/pow-miner-gpu#3]
Hi! I try to run pow-miner-opencl with options - g 0,1,2  or -g 0;1;2 or -g 012 or -g 0+1+2 or -g 0&1&2 or -g 0&&1&&2. But can't run all GPU the same on one instance of pow-miner-opencl.
May be it's run only on multiple instances of PMO (pow-miner-opencl)?
For example 1st instance of PMO GPU0 with option -g0, 2nd inst. of PMO GPU1 with option -g1 and 3rd inst. of PMO GPU2 with option -g2. Only that or conditionally maybe ran with -g All?

**Comment by tontechio** [comment]
This is not an issue, this is a feature.
Every instance of pow-miner is dedicated to GPU. If you have more than one GPU you have to run as much precesses as much GPUs you want to use.

For example, you have 4 GPUs in a system and you want to use first, second and fourth GPU for mining, lets suppose that third GPU already used by different task:

```
$ pow-miner-opencl ... -G 0 ... &
$ pow-miner-opencl ... -G 1 ... &
$ pow-miner-opencl ... -G 3 ... &
```

You can make it in a "nohup" way like in example or run it in a `screen` sessions, `tmux` session or even make a simple systemctl service
