### ISSUE TITLE
In Russian Windows 10 some error messages displayed incorrectly

### ISSUE THREAD

**Issue by KroKoKot** [tontechio/pow-miner-gpu#32]
Hi,

in russian Windows 10 then, for example, disable network, miner stopped with diagnostic messages like this: 

C:\TEMP\minertools-cuda-windows-x86-64>goto _minerstart

C:\TEMP\minertools-cuda-windows-x86-64>tonlib-cuda-cli.exe -V
tonlib-cli build information: [ Commit: 81ca0b840e8cf1b438361e14c2c94d0988f09b76, Date: 2021-11-08 00:19:18 +0300]

C:\TEMP\minertools-cuda-windows-x86-64>tonlib-cuda-cli.exe -v 3 -C global.config.json -e "pminer start kf8gf1PQy4u2kURl-Gz4LbS29eaN4sVdrVQkPO-JL80VhOe6 EQAUAzZsfd4EFEZvgsooc9JRXHvuFr632523HA7g8Sz3oVWsdfww 0 32 0"
[ 3][t 1][2021-11-09 22:18:29.3809655][TonlibClient.cpp:2108][!Tonlib]  Use blockchain name from MASTER config: 'mainnet' (was '')
Tonlib is inited
[ 1][t 1][2021-11-09 22:18:29.4010984][cuda.cpp:81][!console]   [ GPU #0: SM 6.1 NVIDIA GeForce GTX 1080 Ti ]
[ 3][t 1][2021-11-09 22:18:29.4012934][tonlib-cli.cpp:883][!console]    Miner #1 created
synchronization: ???
[ 1][t 0][2021-11-09 22:18:29.4036727][adnl-ext-connection.cpp:129][!outconn]   Client got error [WindowsError : ╨б╨┤╨╡╨╗╨░╨╜╨░ ╨┐╨╛╨┐╤Л╤В╨║╨░ ╨▓╤Л╨┐╨╛╨╗╨╜╨╕╤В╤М ╨╛╨┐╨╡╤А╨░╤Ж╨╕╤О ╨╜╨░ ╤Б╨╛╨║╨╡╤В╨╡ ╨┤╨╗╤П ╨╜╨╡╨┤╨╛╤Б╤В╤Г╨┐╨╜╨╛╨│╨╛ ╤Е╨╛╤Б╤В╨░. : 10065 : Error on [fd:00000000000001F4]]

**Comment by tontechio** [comment]
Looks like firewall/winprotect blocks network miner activity
