### ISSUE TITLE
Benchmark mode always tests GPU #0

### ISSUE THREAD

**Issue by dsglazyrin** [tontechio/pow-miner-gpu#34]
Win10x64. 471.41 driver. Latest release of pow-miner-gpu. Multy-GPU system.
Starting miner in benchmark mode with any value of -g parameter always leads to benchmark of GPU #0

![image](https://user-images.githubusercontent.com/94034279/141067279-be353e68-b70a-443e-8414-702302555d5b.png)

**Comment by tontechio** [comment]
Fix on the way. Thanks

**Comment by tontechio** [comment]
Fixed 
https://github.com/tontechio/pow-miner-gpu/releases/latest
