### ISSUE TITLE
[Error : 0 : Unkwnown query `'pminer`]

### ISSUE THREAD

**Issue by Skandal3713** [tontechio/pow-miner-gpu#39]
hello please tell me what is this error and how to fix it

[ 3][t 1][2021-11-11 09:23:24.1194573][TonlibClient.cpp:2108][!Tonlib]  Use blockchain name from MASTER config: 'mainnet' (was '')
Tonlib is inited
Query {'pminer} FAILED:
        [Error : 0 : Unkwnown query `'pminer`]
[ 1][t 1][2021-11-11 09:23:24.1307330][tonlib-cli.cpp:395][!console]    FAILED

C:\Users\Ventilyator\Desktop\minertools-cuda-windows-x86-64>pause
Для продолжения нажмите любую клавишу . . 
![Снимок экрана (3)](https://user-images.githubusercontent.com/44937169/141273253-43063b3f-0dbd-462b-abf5-9fe486b59a11.png)
.

**Comment by tontechio** [comment]
Please use .bat-files from here:
https://github.com/tontechio/pow-miner-win-util

**Comment by Skandal3713** [comment]
sorry i don't understand how to set them up

**Comment by Skandal3713** [comment]
правильно ли я сделал?
GIVER_ADDR=kf-FV4QTxLl-7Ct3E6MqOtMt-RGXMxi27g4I645lw6MTWraV
MY_ADDR=QD2aeCNRamM9wPuGFUZ4wnMZ627UubOBle-fLU_Vvph7Sv7
GPU_ID=0
GPU_PLATFORM_ID=0
BOOST_FACTOR=64
CONFIG_FILE=global.config.json
USE_LOG=N
LOG_FILE=gpu_0_miner_log.txt
TEST_TIME=10

**Comment by Skandal3713** [comment]
probably my video card is very weak
