### ISSUE TITLE
Can't compile pow-miner-cuda

### ISSUE THREAD

**Issue by rubtsovich** [tontechio/pow-miner-gpu#4]
Hello!
pow-miner-cuda compiles with errors: 
Console output after "/usr/bin/ton$ sudo make -j 8 pow-miner pow-miner-cuda lite-client": 

[ 94%] Built target ton_block
[100%] Building CUDA object crypto/CMakeFiles/pow-miner-cuda-lib.dir/util/cuda/credits.cu.o
[100%] Building CUDA object crypto/CMakeFiles/pow-miner-cuda-lib.dir/util/cuda/cuda_credits.cu.o
/usr/src/pow-miner-gpu/tdutils/td/utils/StackAllocator.h(71): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/tdutils/td/utils/logging.h(202): warning: overloaded virtual function "td::LogInterface::append" is only partially overridden in class "td::NullLog"

/usr/src/pow-miner-gpu/tdutils/td/utils/logging.h(311): warning: overloaded virtual function "td::LogInterface::append" is only partially overridden in class "td::TsLog"

/usr/src/pow-miner-gpu/tdutils/td/utils/StackAllocator.h(71): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/tdutils/td/utils/logging.h(202): warning: overloaded virtual function "td::LogInterface::append" is only partially overridden in class "td::NullLog"

/usr/src/pow-miner-gpu/tdutils/td/utils/logging.h(311): warning: overloaded virtual function "td::LogInterface::append" is only partially overridden in class "td::TsLog"

/usr/src/pow-miner-gpu/crypto/vm/cells/CellSlice.h(45): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/crypto/vm/cells/CellSlice.h(45): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/tdutils/td/utils/buffer.h(127): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/tdutils/td/utils/buffer.h(127): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(735): warning: overloaded virtual function "tlb::TLB::as_integer" is only partially overridden in class "tlb::NatWidth"

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(749): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(862): warning: overloaded virtual function "tlb::TLB::as_integer" is only partially overridden in class "tlb::Int"

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(892): warning: overloaded virtual function "tlb::TLB::as_integer" is only partially overridden in class "tlb::UInt"

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(906): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/crypto/../ton/ton-types.h(33): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(735): warning: overloaded virtual function "tlb::TLB::as_integer" is only partially overridden in class "tlb::NatWidth"

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(749): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(862): warning: overloaded virtual function "tlb::TLB::as_integer" is only partially overridden in class "tlb::Int"

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(892): warning: overloaded virtual function "tlb::TLB::as_integer" is only partially overridden in class "tlb::UInt"

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(906): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/crypto/../ton/ton-types.h(33): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/crypto/util/cuda/credits.cu(37): warning: variable "complexity" was declared but never referenced

/usr/src/pow-miner-gpu/tdutils/td/utils/StackAllocator.h(71): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/tdutils/td/utils/logging.h(202): warning: overloaded virtual function "td::LogInterface::append" is only partially overridden in class "td::NullLog"

/usr/src/pow-miner-gpu/tdutils/td/utils/logging.h(311): warning: overloaded virtual function "td::LogInterface::append" is only partially overridden in class "td::TsLog"

/usr/src/pow-miner-gpu/crypto/vm/cells/CellSlice.h(45): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/tdutils/td/utils/buffer.h(127): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/tdutils/td/utils/StackAllocator.h(71): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/tdutils/td/utils/logging.h(202): warning: overloaded virtual function "td::LogInterface::append" is only partially overridden in class "td::NullLog"

/usr/src/pow-miner-gpu/tdutils/td/utils/logging.h(311): warning: overloaded virtual function "td::LogInterface::append" is only partially overridden in class "td::TsLog"

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(735): warning: overloaded virtual function "tlb::TLB::as_integer" is only partially overridden in class "tlb::NatWidth"

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(749): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(862): warning: overloaded virtual function "tlb::TLB::as_integer" is only partially overridden in class "tlb::Int"

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(892): warning: overloaded virtual function "tlb::TLB::as_integer" is only partially overridden in class "tlb::UInt"

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(906): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/crypto/../ton/ton-types.h(33): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/crypto/vm/cells/CellSlice.h(45): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/tdutils/td/utils/buffer.h(127): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(735): warning: overloaded virtual function "tlb::TLB::as_integer" is only partially overridden in class "tlb::NatWidth"

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(749): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(862): warning: overloaded virtual function "tlb::TLB::as_integer" is only partially overridden in class "tlb::Int"

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(892): warning: overloaded virtual function "tlb::TLB::as_integer" is only partially overridden in class "tlb::UInt"

/usr/src/pow-miner-gpu/crypto/tl/tlblib.hpp(906): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/crypto/../ton/ton-types.h(33): warning: integer conversion resulted in a change of sign

/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/functional/function_ref.h:101:29: error: parameter packs not expanded with ‘...’:
   template <typename F, typename = EnableIfCompatible<const F&>>
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/functional/function_ref.h:101:29: note:         ‘Args’
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/functional/function_ref.h:116:13: error: parameter packs not expanded with ‘...’:
       typename F, typename = EnableIfCompatible<F*>,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/functional/function_ref.h:116:13: note:         ‘Args’
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/strings/cord.h: In instantiation of ‘H absl::Cord::HashFragmented(H) const [with H = absl::hash_internal::MixingHashState]’:
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/strings/cord.h:662:48:   required from ‘H absl::AbslHashValue(H, const absl::Cord&) [with H = absl::hash_internal::MixingHashState]’
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/hash/internal/hash.h:661:21:   required from ‘static absl::enable_if_t<std::is_same<H, decltype (absl::hash_internal::AbslHashValue(std::move(state), value))>::value, H> absl::hash_internal::HashSelect::HashValueProbe::Invoke(H, const T&) [with H = absl::hash_internal::MixingHashState; T = absl::Cord; absl::enable_if_t<std::is_same<H, decltype (absl::hash_internal::AbslHashValue(std::move(state), value))>::value, H> = absl::hash_internal::MixingHashState]’
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/hash/internal/hash.h:998:64:   required from ‘static H absl::hash_internal::HashStateBase<H>::combine(H, const T&, const Ts& ...) [with T = absl::Cord; Ts = {}; H = absl::hash_internal::MixingHashState]’
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/hash/internal/hash.h:768:36:   required from ‘static size_t absl::hash_internal::MixingHashState::hash(const T&) [with T = absl::Cord; typename std::enable_if<(! absl::conjunction<std::is_integral<_Tp>, absl::hash_internal::is_uniquely_represented<T, void> >::value), int>::type <anonymous> = 0; size_t = long unsigned int]’
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/hash/internal/hash.h:987:29:   required from ‘size_t absl::hash_internal::HashImpl<T>::operator()(const T&) const [with T = absl::Cord; size_t = long unsigned int]’
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/container/internal/hash_function_defaults.h:77:24:   required from here
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/strings/cord.h:894:1: error: no matching function for call to ‘absl::Cord::ForEachChunk(absl::Cord::HashFragmented(H) const [with H = absl::hash_internal::MixingHashState]::<lambda(absl::string_view)>) const’
     ForEachChunk([&combiner, &hash_state](absl::string_view chunk) {
 ^
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/strings/cord.h:1424:13: note: candidate: ‘void absl::Cord::ForEachChunk(absl::FunctionRef<void(absl::string_view)>) const’
 inline void Cord::ForEachChunk(
             ^~~~
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/strings/cord.h:1424:13: note:   no known conversion for argument 1 from ‘absl::Cord::HashFragmented(H) const [with H = absl::hash_internal::MixingHashState]::<lambda(absl::string_view)>’ to ‘absl::FunctionRef<void(absl::string_view)>’
make[3]: *** [crypto/CMakeFiles/pow-miner-cuda-lib.dir/build.make:115: crypto/CMakeFiles/pow-miner-cuda-lib.dir/util/cuda/credits.cu.o] Ошибка 1
make[3]: *** Ожидание завершения заданий…
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/functional/function_ref.h:101:29: error: parameter packs not expanded with ‘...’:
   template <typename F, typename = EnableIfCompatible<const F&>>
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/functional/function_ref.h:101:29: note:         ‘Args’
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/functional/function_ref.h:116:13: error: parameter packs not expanded with ‘...’:
       typename F, typename = EnableIfCompatible<F*>,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/functional/function_ref.h:116:13: note:         ‘Args’
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/strings/cord.h: In instantiation of ‘H absl::Cord::HashFragmented(H) const [with H = absl::hash_internal::MixingHashState]’:
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/strings/cord.h:662:48:   required from ‘H absl::AbslHashValue(H, const absl::Cord&) [with H = absl::hash_internal::MixingHashState]’
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/hash/internal/hash.h:661:21:   required from ‘static absl::enable_if_t<std::is_same<H, decltype (absl::hash_internal::AbslHashValue(std::move(state), value))>::value, H> absl::hash_internal::HashSelect::HashValueProbe::Invoke(H, const T&) [with H = absl::hash_internal::MixingHashState; T = absl::Cord; absl::enable_if_t<std::is_same<H, decltype (absl::hash_internal::AbslHashValue(std::move(state), value))>::value, H> = absl::hash_internal::MixingHashState]’
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/hash/internal/hash.h:998:64:   required from ‘static H absl::hash_internal::HashStateBase<H>::combine(H, const T&, const Ts& ...) [with T = absl::Cord; Ts = {}; H = absl::hash_internal::MixingHashState]’
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/hash/internal/hash.h:768:36:   required from ‘static size_t absl::hash_internal::MixingHashState::hash(const T&) [with T = absl::Cord; typename std::enable_if<(! absl::conjunction<std::is_integral<_Tp>, absl::hash_internal::is_uniquely_represented<T, void> >::value), int>::type <anonymous> = 0; size_t = long unsigned int]’
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/hash/internal/hash.h:987:29:   required from ‘size_t absl::hash_internal::HashImpl<T>::operator()(const T&) const [with T = absl::Cord; size_t = long unsigned int]’
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/container/internal/hash_function_defaults.h:77:24:   required from here
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/strings/cord.h:894:1: error: no matching function for call to ‘absl::Cord::ForEachChunk(absl::Cord::HashFragmented(H) const [with H = absl::hash_internal::MixingHashState]::<lambda(absl::string_view)>) const’
     ForEachChunk([&combiner, &hash_state](absl::string_view chunk) {
 ^
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/strings/cord.h:1424:13: note: candidate: ‘void absl::Cord::ForEachChunk(absl::FunctionRef<void(absl::string_view)>) const’
 inline void Cord::ForEachChunk(
             ^~~~
/usr/src/pow-miner-gpu/third-party/abseil-cpp/absl/strings/cord.h:1424:13: note:   no known conversion for argument 1 from ‘absl::Cord::HashFragmented(H) const [with H = absl::hash_internal::MixingHashState]::<lambda(absl::string_view)>’ to ‘absl::FunctionRef<void(absl::string_view)>’
make[3]: *** [crypto/CMakeFiles/pow-miner-cuda-lib.dir/build.make:128: crypto/CMakeFiles/pow-miner-cuda-lib.dir/util/cuda/cuda_credits.cu.o] Ошибка 1
make[2]: *** [CMakeFiles/Makefile2:9178: crypto/CMakeFiles/pow-miner-cuda-lib.dir/all] Ошибка 2
make[1]: *** [CMakeFiles/Makefile2:8721: crypto/CMakeFiles/pow-miner-cuda.dir/rule] Ошибка 2
make: *** [Makefile:2138: pow-miner-cuda] Ошибка 2

I would be grateful if you can tell me what needs to be fixed.

**Comment by jetaweb** [comment]
Hi, and me too)  I’ve got the same errors.

**Comment by tontechio** [comment]
Fixed in 31be6e4
