### ISSUE TITLE
OpenCL miner works only on first 2 GPUs.

### ISSUE THREAD

**Issue by maratsarbasov** [tontechio/pow-miner-gpu#48]
Hello, I have 7 RX580 GPUs:

```
[ OpenCL: platform #0 device #0 Ellesmere ]
[ OpenCL: platform #0 device #1 Ellesmere ]
[ OpenCL: platform #0 device #2 Ellesmere ]
[ OpenCL: platform #0 device #3 Ellesmere ]
[ OpenCL: platform #0 device #4 Ellesmere ]
[ OpenCL: platform #0 device #5 Ellesmere ]
[ OpenCL: platform #0 device #6 Ellesmere ]
[ OpenCL: platform #1 device #0 Intel(R) HD Graphics ]
[ OpenCL: platform #1 device #1 Intel(R) Celeron(R) CPU G1840 @ 2.80GHz ]
```

Miner works only if I set (platform=0, device=0) and (platform=0, device=1). If I set any other device id (from 2 to 6) I get the following error:
`Error 749353232 executing clGetDeviceInfo(devices_[device_idx], CL_DEVICE_NAME, sizeof(buf), buf, NULL) on D:\a\pow-miner-gpu\pow-miner-gpu\crypto\util\opencl\opencl.cpp:77 (invalid/unknown error code)
[pid 3400] [time 1636733282] Signal: 22`
or 
`Error -33 executing clGetDeviceInfo(devices_[device_idx], CL_DEVICE_NAME, sizeof(buf), buf, NULL) on D:\a\pow-miner-gpu\pow-miner-gpu\crypto\util\opencl\opencl.cpp:77 (invalid device)
[pid 7960] [time 1636733501] Signal: 22`

**Comment by DelphiR** [comment]
This might be fixed during the last release: https://github.com/tontechio/pow-miner-gpu/releases/tag/20211112-3
Check it. We wait your answer
