### ISSUE TITLE
Ошибка при запуске майнера и теста

### ISSUE THREAD

**Issue by total105** [tontechio/pow-miner-gpu#49]
При запуске обновленного майнера и теста на лучший boost factor появляются ошибки, майнинг не запускается.
Win 10 x64 professional
1xRX570 4Gb
Драйвера последние с сайта AMD
![Before Min](https://user-images.githubusercontent.com/94188302/141498919-5c440c81-2fc3-4708-8820-5ca99699378f.jpg)
![BEST BOOT](https://user-images.githubusercontent.com/94188302/141498930-73999d5d-263a-4b97-a85b-bca0c7329bd0.jpg)

**Comment by DelphiR** [comment]
Вы запускали первый раз, файл кеша не был создан и вам не повезло - попали на лайт сервер, который был out of sуnc, либо вы использовали свой собственный LS
сейчас вам нужно убедить, чтобы скачали самый свежий https://newton-blockchain.github.io/global.config.json
И повторить ваш запуск на последней версии майнера

**Comment by IncognitoBA** [comment]
NVIDIA GeForce GTX650
При запуске test_cuda.bat приложение аварийно завершает работу:
![image](https://user-images.githubusercontent.com/17872683/141645989-9ed243cb-391f-4bbc-b147-49a17dc7443d.png)

В консоли:
![image](https://user-images.githubusercontent.com/17872683/141646087-1d507348-d3b2-42c0-bf2b-a865f11775fc.png)

**Comment by DelphiR** [comment]
> NVIDIA GeForce GTX650 При запуске test_cuda.bat приложение аварийно завершает работу: ![image](https://user-images.githubusercontent.com/17872683/141645989-9ed243cb-391f-4bbc-b147-49a17dc7443d.png)
> 
> В консоли: ![image](https://user-images.githubusercontent.com/17872683/141646087-1d507348-d3b2-42c0-bf2b-a865f11775fc.png)

Используйте opencl версию для этой модели видеокарты

**Comment by DelphiR** [comment]
Если  фидбека не будет, то скорее всего совет с opencl помог и issue можно закрыть
Для вашей видеокарты следует использовать версию майнера для старых систем, но мы ее так до сих пор и не выдали в аудиторию

**Comment by IncognitoBA** [comment]
> Если фидбека не будет, то скорее всего совет с opencl помог и issue можно закрыть Для вашей видеокарты следует использовать версию майнера для старых систем, но мы ее так до сих пор и не выдали в аудиторию

@DelphiR , да, помогло. Спасибо за быстрый ответ!
