### ISSUE TITLE
Installation instructions on Ubuntu

### ISSUE THREAD

**Issue by jumpingfella** [tontechio/pow-miner-gpu#6]
Hello,

I tried to compile this, but got the following:
```
CMake Error at CMakeLists.txt:356 (get_target_property):
  get_target_property() called with non-existent target
  "absl::flat_hash_map".
```

**Comment by tontechio** [comment]
It seems like `abseil-cpp` submodule is missed. You should use the `--recursive` flag when cloning a repository. This parameter forces git to clone all defined submodules in the repository.
