### ISSUE TITLE
error ton-coin    "Use blockchain name from MASTER config: 'mainnet' (was '')" no sync

### ISSUE THREAD

**Issue by Vlad6250** [tontechio/pow-miner-gpu#61]
C:\Users\Admin\Desktop\minertools-cuda-windows-x86-64>tonlib-cuda-cli.exe -v 3 -C global.config.json -e "pminer start kf-kkdY_B7p-77TLn2hUhM6QidWrrsl8FYWCIvBMpZKprBtN EQDXRzX4Qnmsjig1nHWw7ATGHbs9qTG251Kholm2x6Q9gd6V 0 32"
[ 3][t 1][2021-11-16 14:27:21.4581118][TonlibClient.cpp:2108][!Tonlib]  Use blockchain name from MASTER config: 'mainnet' (was '')
[ 2][t 1][2021-11-16 14:27:21.4650366][tonlib-cli.cpp:285][!console]    Tonlib is inited
[ GPU #0: SM 6.1 NVIDIA GeForce GTX 1080 Ti ]
[ GPU #1: SM 6.1 NVIDIA GeForce GTX 1080 Ti ]
[ GPU #2: SM 6.1 NVIDIA GeForce GTX 1080 Ti ]
[ GPU #3: SM 6.1 NVIDIA GeForce GTX 1080 Ti ]
[ 3][t 1][2021-11-16 14:27:21.5548087][tonlib-cli.cpp:885][!console]    Miner #1 created
[ 3][t 2][2021-11-16 14:27:21.8455524][tonlib-cli.cpp:1782][!console]   Time diff with liteserver: 893.2s
[ 1][t 2][2021-11-16 14:27:21.8458317][tonlib-cli.cpp:904][!console]    [Error : 0 : Your system time is out of sync]

**Comment by mx5team** [comment]
try to synchronize the time

https://answers.microsoft.com/en-us/windows/forum/all/how-to-force-windows-10-time-to-synch-with-a-time/20f3b546-af38-42fb-a2d0-d4df13cc8f43

**Comment by Vlad6250** [comment]
спасибо помогло
