### ISSUE TITLE
File global.config.json can't be opened for reading

### ISSUE THREAD

**Issue by mx5team** [tontechio/pow-miner-gpu#62]
`  ton/tonlib-cuda-cli -v 3 -C global.config.json -e 'pminer start kf8gf1PQy4u2kURl-Gz4LbS29eaN4sVdrVQkPO-JL80VhOe6 EQDf7DdGn96UXKn3o_kI2j7FYMPhhMhb2pZrYcsq9mqddfP5 0 8 0'  `

![image](https://user-images.githubusercontent.com/91607413/142006962-0fda270d-6dd3-42b1-bb39-c31e2b6618e2.png)

tried to change the permissions to the file and directory in different combinations and for different groups - it does not work

![image](https://user-images.githubusercontent.com/91607413/142007169-6faaa898-4fce-4ce0-b6ab-b6a29dc94fea.png)

**Comment by Dirlandets** [comment]
Запускаете скрипт из той же дирректории в которой tonlib-cuda-cli?
Судя по всему нет.

**Comment by mx5team** [comment]
в той же директории все файлы 

![image](https://user-images.githubusercontent.com/91607413/142059621-b6640f25-24b5-4276-a6e8-d77e105e4263.png)

иначе бы он написал ошибку, что файл не найден

**Comment by Dirlandets** [comment]
Бросьте фаил с конфигом в корневой каталог на один уровень с /opt /etc

Либо укажите к нему полный путь.

**Comment by mx5team** [comment]
> Бросьте фаил с конфигом в корневой каталог на один уровень с /opt /etc
> 
> Либо укажите к нему полный путь.



thanks! problem solved by Setting full path to the _global.config.json_

**Comment by magistrigusti** [comment]
C:\Users\magis\Desktop\minertools-cuda-windows-x86-64>tonlib-cuda-cli.exe -V
tonlib-cli build information: [ Commit: 5bb3442325f500e5f78b8ae5c3473283d4271dd9, Date: 2021-12-16 16:59:57 +0300]

C:\Users\magis\Desktop\minertools-cuda-windows-x86-64>tonlib-cuda-cli.exe -v 3 -C global.config.json -e "pminer start EQATFtnrnDB6wCRujkPSQGVmK3GjmLUDMqN6QgnY4mKK_Szp EQApy0S2CA-khsK439phmlLPuwbLD5CPUKPyqDIrerwIwLJr 0 64 0"
[ 1][t 1][2021-12-17 14:34:57.9098323][tonlib-cli.cpp:278][!console][&r_ok.is_error()]  [Error : 400 : INVALID_CONFIG: can't parse configOpening '"' expected]


Что делать браты? Не успел отключить антивирус он сук закинул какойто файл к себе сук но я ему дал по рогам и все вернул но после все совсем сломалос. Подскажите пожалуйста а то я смотрю видос и делаю как там но не ху не работает. Сук даже палец повредил. Пожалуста помогите решить еба ную проблему терения больше нет

**Comment by magistrigusti** [comment]
> Бросьте фаил с конфигом в основной каталог на один уровень с / opt / etc
> 
> Либо укажите к нему полный путь.

напиши пожалуйста литературным языком ты же не для себя тут пишешь для себя можно в туалете на стене там любой сленг пойдет. Если ты дествительно что то понимаешь из того что ты тут писал. То будь мать его за ногу так мил и напиши на языке понятном человеку или языке который возможно перевести или итропретировать без допроса с пристрастием для тебя. Хоть бы один знающий.
