### ISSUE TITLE
tonlib-cli claims "No Lite Servers"

### ISSUE THREAD

**Issue by optimizmo** [tontechio/pow-miner-gpu#68]
Может быть, я что-то упустил, но при вызове

> /usr/bin/ton/tonlib/tonlib-cli
> \>runmethod <wallet> getTransactions

я получаю

> [ 1][t 1][2021-11-17 16:56:55.287391943][tonlib-cli.cpp:1501][!console]	 vs 
> Run smc_methodIdName {
>   name = "getTransactions"
> }
> With stack:
> Query {runmethod <wallet> getTransactions} FAILED: 
> 	[Error : 500 : NO_LITE_SERVERS]

Майнер при этом работает, значит, метод get_pow_params, похоже, вызывается. Как это починить?

**Comment by tontechio** [comment]
Нужно указать конфиг сети.
Список параметров:
`tonlib-cli -h`

**Comment by optimizmo** [comment]
Спасибо, понял. Сделал:
> wget https://newton-blockchain.github.io/global.config.json

и стал запускать с 

`tonlib-cli -c global.config.json`

Ошибка пропала.
