### ISSUE TITLE
 [Error : 500 : LITE_SERVER_NETWORKadnl query timeout]

### ISSUE THREAD

**Issue by AndCry47** [tontechio/pow-miner-gpu#69]
Здравствуйте, вводные данные такие - у меня есть 2е машины обе находятся в одной сети запитаны с одного роутера, настройки одинаковые:

1. Ryzen 5 3600, ASRock B450M Pro4, RTX 2060s - майнится все отлично, проблем нет
2. Q9550, Gigabyte GA-P41T-D3P v1.3, RX 460 - сыпет ошибки ЛСа, тест проходит, а майнинг не запускает по причине ошибки на скрине. Крокозябра расшифровывается как - Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. Пробовал подключаться через ProtonVPN - результата не дало.
![image](https://user-images.githubusercontent.com/83208027/142394883-a2754f3e-486a-4408-814b-d301a54339b5.png)
Подключаюсь на Машине 2 к Машине 1 по RDP(кстати, тоже есть вопрос, почему падает Хеш в ~2 раза при закрытии окна RPD? Приходится всегда держать RPD в открытом состоянии)

**Comment by tontechio** [comment]
1. Работу под RDP не проверяли и не исследовали, это выходит за рамки задачи
2. Error : 500 - это чисто сетевая проблема, к самому майнеру отношения не имеет

Майнер выбирает ЛС случайным образом из конфига. 

Могу посоветовать убирать из global.config.json тот лайт-сервер, с которым возникла ошибка. Его можно найти по строчке из ошибки `(#2276822237)`, искать в конфиге по `2276822237`. Может помочь убрать из случайного перебора лайтсерверов тех, с которыми точно есть проблемы соединения

**Comment by AndCry47** [comment]
> 1. Работу под RDP не проверяли и не исследовали, это выходит за рамки задачи
> 2. Error : 500 - это чисто сетевая проблема, к самому майнеру отношения не имеет
> 
> Майнер выбирает ЛС случайным образом из конфига.
> 
> Могу посоветовать убирать из global.config.json тот лайт-сервер, с которым возникла ошибка. Его можно найти по строчке из ошибки `(#2276822237)`, искать в конфиге по `2276822237`. Может помочь убрать из случайного перебора лайтсерверов тех, с которыми точно есть проблемы соединения

Нет таких значений в конфиге, да и проблемный апишник в ошибке пишет крайне редко, вот например -
![image](https://user-images.githubusercontent.com/83208027/142449751-ef3a291d-cf78-4510-a700-59d37fc3a7ec.png)

За 5 минут работы выдал еще один проблемный айпи под номером #3158628591 , но в конфиге открытом в блокноте не ищется не предыдущий не этот... в чем дело?
![image](https://user-images.githubusercontent.com/83208027/142450124-58024965-900a-4ece-842d-ba62c5cc3e2b.png)
![image](https://user-images.githubusercontent.com/83208027/142450197-d1b260b8-fb9b-475b-a97c-40269067a23b.png)
Что делаю не так?

**Comment by tontechio** [comment]
Все так. Была ошибка в отображении сообщения. В следующем релизе будет фикс и по этому номеру можно будет находить ЛС, к которым конкретно со стороны майнера проблемы с коннектом

**Comment by AndCry47** [comment]
> Все так. Была ошибка в отображении сообщения. В следующем релизе будет фикс и по этому номеру можно будет находить ЛС, к которым конкретно со стороны майнера проблемы с коннектом

отличные новости, но по факту это не решает пробелму, подключения к ЛСам не происходят, цикл подключений(и ошибок) продолжается и не подключается не к одному ЛСу, есть подозрение что дело в старом железе(мат. плате/сетевухе), что можете сказать по этому поводу? Куда можно еще покопать в этой проблеме?
