### ISSUE TITLE
Optimal Number of GPU Threads for cuda

### ISSUE THREAD

**Issue by ehadiev** [tontechio/pow-miner-gpu#7]
Hi!
I'm trying to calculate GPU Threads as described /crypto/util/pow-miner-howto.md
crypto/pow-miner worked well

in my PC has 3D controller: NVIDIA 
and when I run 
crypto/pow-miner-cuda 
I get:

GPU #0: SM 7.5 Tesla T4
[ expected required hashes for success: 3921112346559999 ]
not found!

what could be the problem?
How can I get in debug mode?

**Comment by ehadiev** [comment]
![image](https://user-images.githubusercontent.com/35795919/137294858-343a93ad-6f39-4357-82ba-206f81bd2fc3.png)

**Comment by tontechio** [comment]
Which parameters did you'd used to run the gpu miner?
