### ISSUE TITLE
Использование собственного Lite server

### ISSUE THREAD

**Issue by nitrogenium** [tontechio/pow-miner-gpu#70]
Позволю себе написать вопрос на русском, если вы не против.

Как использовать собственный lite server?

Удаленно я могу к нему подключится используя:

`$ lite-client -a <IP>:<TCP-PORT> -p liteserver.pub`

Как я понимаю нужно поправить **global.config.json** оставит там только свой сервер.

Вот пример секции из этого файла:

```
  "liteservers": [
    {
      "ip": 1137658550,
      "port": 4924,
      "id": {
        "@type": "pub.ed25519",
        "key": "peJTw/arlRfssgTuf9BMypJzqOi7SXEqSPSWiEw2U1M="
      }
    },
    {
      "ip": 84478511,
      "port": 19949,
      "id": {
        "@type": "pub.ed25519",
        "key": "n4VDnSCUuSpjnCyUk9e3QOOd6o0ItSWYbTnW3Wnn8wk="
      }
    },
....
....
}
```

в каком виде задается ip? Там просто число, или это не ip ?
@type - кокой указывать? Такой же оставлять?
key - что это? Откуда его взять.

Помогите разобраться плиз. Я в свою очередь составлю мануал на 2х языках. Ведь чем больше lite серверов тем лучше для сети

**Comment by jetaweb** [comment]
Для получения параметров используйте 

mytonctrl -> installer > plsc

**Comment by tontechio** [comment]
> Как я понимаю нужно поправить global.config.json оставит там только свой сервер.

верно
