### ISSUE TITLE
GPU openCL start problem

### ISSUE THREAD

**Issue by gsmcenter** [tontechio/pow-miner-gpu#71]
I have problem with start on GPU. 
I have 6 GPU RX470 (openCL)
Windows 10

and after start seed suggest me that is calc only on GPU.

GIVER_ADDR=kf-kkdY_B7p-77TLn2hUhM6QidWrrsl8FYWCIvBMpZKprBtN
MY_ADDR=EQAHDFEAt0I1sMAZMqUiL-PIRzWIK4CR2cWQ-EswyMwzX5qd
GPU_ID=1
GPU_PLATFORM_ID=1
BOOST_FACTOR=1024
CONFIG_FILE=global.config.json
USE_LOG=N
LOG_FILE=gpu_0_miner_log.txt
TEST_TIME=10

run_opencl.bat >>>

minertools-opencl-windows-x86-64>tonlib-opencl-cli.exe -V
tonlib-cli build information: [ Commit: b44bffbffa900c56489cc9586c873adaa5b0bd25, Date: 2021-11-16 19:38:32 +0300]

minertools-opencl-windows-x86-64>tonlib-opencl-cli.exe -v 3 -C global.config.json -e "pminer start kf-kkdY_B7p-77TLn2hUhM6QidWrrsl8FYWCIvBMpZKprBtN EQAHDFEAt0I1sMAZMqUiL-PIRzWIK4CR2cWQ-EswyMwzX5qd 1 1024 1"
[ 3][t 1][2021-11-18 13:23:55.8433173][TonlibClient.cpp:2108][!Tonlib]  Use blockchain name from MASTER config: 'mainnet' (was '')
[ 2][t 1][2021-11-18 13:23:55.8697903][tonlib-cli.cpp:285][!console]    Tonlib is inited
[ 3][t 1][2021-11-18 13:23:55.8699107][tonlib-cli.cpp:888][!console]    Miner #1 created
[ 2][t 1][2021-11-18 13:23:56.0604297][tonlib-cli.cpp:801][!PowMiner]   pminer: got new options from kf-kkdY_B7p-77TLn2hUhM6QidWrrsl8FYWCIvBMpZKprBtN, seed=257705875437526090882464354053219453845, complexity=68790546812207893243051043754084983934488383274853527277547033
[ 3][t 1][2021-11-18 13:23:56.0605150][tonlib-cli.cpp:806][!PowMiner]   [ expected required hashes for success: 1683255833878139 ]
[ 3][t 1][2021-11-18 13:23:56.0611703][tonlib-cli.cpp:674][!PowMiner]   pminer: start workers
[ OpenCL: set kernel source (17937 bytes) ]
[ OpenCL: platform #0 device #0 Intel(R) HD Graphics 510 ]
[ OpenCL: platform #0 device #1 Intel(R) Celeron(R) CPU G3900 @ 2.80GHz ]
[ OpenCL: platform #1 device #0 Ellesmere ]
[ OpenCL: platform #1 device #1 Ellesmere ]
[ OpenCL: platform #1 device #2 Ellesmere ]
[ OpenCL: platform #1 device #3 Ellesmere ]
[ OpenCL: platform #1 device #4 Ellesmere ]
[ OpenCL: platform #1 device #5 Ellesmere ]
[ OpenCL: create context for platform #1 device #1 Ellesmere, max work group size is 256 ]
[ 2][t 4][2021-11-18 13:23:59.0432128][sha256.cpp:29]   [ START MINER, GPU ID: 1, boost factor: 1024, throughput: 536870912 ]
[ 3][t 4][2021-11-18 13:24:00.7900706][Miner.cpp:104]   [ mining in progress, passed: 4728.8ms, hashes computed: 536870912, instant speed: 307.681 Mhash/s, average speed: 113.532 Mhash/s ]
[ 3][t 1][2021-11-18 13:24:01.2097893][tonlib-cli.cpp:797][!PowMiner]   mining seed 2577...3845
[ 3][t 4][2021-11-18 13:24:06.0170965][Miner.cpp:104]   [ mining in progress, passed: 9955.8ms, hashes computed: 2147483648, instant speed: 308.143 Mhash/s, average speed: 215.701 Mhash/s ]
[ 3][t 2][2021-11-18 13:24:06.9615252][tonlib-cli.cpp:797][!PowMiner]   mining seed 2577...3845

any idea ?

**Comment by tontechio** [comment]
Can't see any problem in the output provided

**Comment by gsmcenter** [comment]
instant speed: 308.143 
thats is correct  for 6 GPU (AMD RX470) ?

**Comment by gsmcenter** [comment]
i see 100% usage just one one GPU. So i need open this app 6 time with different settings ?

**Comment by tontechio** [comment]
> i see 100% usage just one one GPU. So i need open this app 6 time with different settings ?

correct. Each process (copy) for each GPU
