### ISSUE TITLE
Now use more GPU

### ISSUE THREAD

**Issue by golosoff** [tontechio/pow-miner-gpu#78]
Hi, Can i use more GPU, how i must configure run_config for this?

**Comment by Dirlandets** [comment]
Firstly I recommend you to start test:

```
/opt/ton-miner/pow-miner-cuda -vv \
  -g <YOUR_GPU_ID> \ 
  -B -F 16 -t 10 kQBWkNKqzCAwA9vjMwRmg7aY75Rf8lByPA9zKXoqGkHi8SM7 \
  229760179690128740373110445116482216837 \
  5391989333430127958933403017403926134727428884508114496220722049840 \
  10000000000000000000
  ```
 
  Where <YOUR_GPU_ID> is your GPU id. For example, 0 is your first GPU.
  
  Then when it returns some recommended Boost Factor start using it in the start command.
  For example:
  ```/opt/ton-miner/tonlib-cuda-cli -v 2 -C global.conf.json -e 'pminer start <GIVER_ADDRESS> <MY_ADDRESS> <GPU_ID> <BOOST_FACTOR> <PLATFORM_ID>'```
  
  Where the <BOOST_FACTOR> is recommended Boost Factor:

BUT! I highly recommend you to track the temperature of your GPU and hash rate and increase or lower this rate if temperature or hash rate is go down or up,
