### ISSUE TITLE
Майнер перезапускается, но не показывает ни одной ошибки

### ISSUE THREAD

**Issue by Dem0N-SPb** [tontechio/pow-miner-gpu#80]
Запускаю майнер на риге из 5 GTX 1060 3Gb. 

C:\minertools-cuda-windows-x86-64>tonlib-cuda-cli.exe -V
tonlib-cli build information: [ Commit: e624a4b82cab7e3a85817caa39e07691bcf4235f, Date: 2021-11-19 11:40:06 +0300]

C:\minertools-cuda-windows-x86-64>tonlib-cuda-cli.exe -v 3 -C global.config.json -e "pminer start kf8JfFUEJhhpRW80_jqD7zzQteH6EBHOzxiOhygRhBdt4z2N EQBCrQBR74rSjgKe7zFW4PJZYQPtc7HZwIaM6sPXKm37EjjY 4 512 0" -l gpu_4_miner_log.txt
Miner started, all output to <gpu_4_miner_log.txt>

Перезапускается без единой ошибки.

`[ 3][t 1][2021-11-19 14:39:08.7923342][TonlibClient.cpp:2108][!Tonlib]	Use blockchain name from MASTER config: 'mainnet' (was '')
[ 2][t 1][2021-11-19 14:39:08.8935016][tonlib-cli.cpp:286][!console]	Tonlib is inited
[ GPU #0: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #1: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #2: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #3: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #4: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ 3][t 1][2021-11-19 14:39:09.1231276][tonlib-cli.cpp:906][!console]	Miner #1 created
[ 3][t 1][2021-11-19 14:39:10.7441999][TonlibClient.cpp:2108][!Tonlib]	Use blockchain name from MASTER config: 'mainnet' (was '')
[ 2][t 1][2021-11-19 14:39:10.8807726][tonlib-cli.cpp:286][!console]	Tonlib is inited
[ GPU #0: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #1: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #2: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #3: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #4: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ 3][t 1][2021-11-19 14:39:11.1063408][tonlib-cli.cpp:906][!console]	Miner #1 created
[ 3][t 1][2021-11-19 14:39:12.5366312][TonlibClient.cpp:2108][!Tonlib]	Use blockchain name from MASTER config: 'mainnet' (was '')
[ 2][t 1][2021-11-19 14:39:12.6384929][tonlib-cli.cpp:286][!console]	Tonlib is inited
[ GPU #0: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #1: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #2: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #3: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #4: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ 3][t 1][2021-11-19 14:39:12.9050397][tonlib-cli.cpp:906][!console]	Miner #1 created
[ 3][t 1][2021-11-19 14:39:13.7456624][TonlibClient.cpp:2108][!Tonlib]	Use blockchain name from MASTER config: 'mainnet' (was '')
[ 2][t 1][2021-11-19 14:39:13.8412747][tonlib-cli.cpp:286][!console]	Tonlib is inited
[ GPU #0: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #1: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #2: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #3: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ GPU #4: SM 6.1 NVIDIA GeForce GTX 1060 3GB ]
[ 3][t 1][2021-11-19 14:39:14.1623777][tonlib-cli.cpp:906][!console]	Miner #1 created
`
test_cuda.bat отрабатывает отлично, доходит до конца.

Win10 1607 (14393.1593)
Nvidia 472.12

**Comment by tontechio** [comment]
Сделай подробный репортинг (`-v 4`) и лог сюда прикрепленным файлом плз

**Comment by Dem0N-SPb** [comment]
[gpu_4_miner_log.txt](https://github.com/tontechio/pow-miner-gpu/files/7576762/gpu_4_miner_log.txt)

**Comment by optimis3232** [comment]
А как можно tontechio в личку написать ?

**Comment by tontechio** [comment]
По логу непонятно, рекомендую обновиться до
https://github.com/tontechio/pow-miner-gpu/releases/latest

И обновить global.config.json
