### ISSUE TITLE
Расход трафика и нагрузка на сеть

### ISSUE THREAD

**Issue by nitrogenium** [tontechio/pow-miner-gpu#81]
Каждый процесс майнера нагружает сеть. Учитывая что на каждую карту свой процесс таких процессов может быть много.
Причем нагрузка постоянная, а не только как меняется seed. (Может это баг?)
**Пример: каждый tonlib-opencl-cli в среднем 5 KB/Sec**  =>Ферма из 8 карт это уже 320 килобит в сек.

Из за этого постоянно: 
`Error : 500 : LITE_SERVER_NETWORKadnl query timeout(during last block synchronization)]`

Есть способы уменьшить трафик? Например можно ли поставить lite server в локальной сети что вы сократить потребление трафика в интернет. Например у меня канал в интернет 2Mbit

Есть любые советы?

**Comment by tontechio** [comment]
Расширять канал. Майнер каждые 5 сек проверяет гивер на предмет актуальности текущий задачи.
