### ISSUE TITLE
code = 400  message = "INVALID_PUBLIC_KEYNot a public key"

### ISSUE THREAD

**Issue by xor85** [tontechio/pow-miner-gpu#82]
tonlib-opencl-cli -v 4 -C global.config.json -e 'pminer start kf91o4NNTryJ-Cw3sDGt9OTiafmETdVFUMvylQdFPoOxIsLm EQCMNDafUgyLi9p3uPbqbD7eM8zc9mw0v7YF06W80N82sRXV 0 32'

in log I see thith srtings:

....................................................................................................................................................................................
  initial_account_state = wallet_v3_initialAccountState {
    public_key = "kf91o4NNTryJ-Cw3sDGt9OTiafmETdVFUMvylQdFPoOxIsLm"
    wallet_id = 698983191
  }
  revision = 0
  workchain_id = 0
}
[ 4][t 1][2021-11-20 13:07:50.316586834][TonlibClient.cpp:1529][!console][&tonlib_query]          answer static query error {
  code = 400
  message = "INVALID_PUBLIC_KEYNot a public key"
}
[ 4][t 1][2021-11-20 13:07:50.316619712][TonlibClient.cpp:1521][!console][&tonlib_query]        Tonlib got static query getAccountAddress {
  initial_account_state = wallet_v3_initialAccountState {
    public_key = "EQCMNDafUgyLi9p3uPbqbD7eM8zc9mw0v7YF06W80N82sRXV"
    wallet_id = 698983191
  }
  revision = 0
  workchain_id = 0
}
[ 4][t 1][2021-11-20 13:07:50.316680599][TonlibClient.cpp:1529][!console][&tonlib_query]          answer static query error {
  code = 400
  message = "INVALID_PUBLIC_KEYNot a public key"
}
[ 3][t 1][2021-11-20 13:07:50.316717858][tonlib-cli.cpp:906][!console]  Miner #1 created
[ 4][t 1][2021-11-20 13:07:50.316808857][TonlibClient.cpp:1482][!Tonlib][&tonlib_query] Tonlib got query [id:2] liteServer_getInfo {
....................................................................................................................................................................................

Is this normal?, or I not be rewarded because of this error?

**Comment by tontechio** [comment]
This is normal. Just extended reporting (almost debug mode)
