### ISSUE TITLE
Error -36 executing clFinish(command_queue_) on D:\a\pow-miner-gpu\pow-miner-gpu\crypto\util\opencl\opencl.cpp:228 (invalid command queue) [pid 8224] [time 1637501583] Signal: 22

### ISSUE THREAD

**Issue by IncognitoBA** [tontechio/pow-miner-gpu#83]
Сегодня обновил miner до 20211119-4.
На предыдущей версии не замечал (возможно тоже было).
Полный лог:
`C:\minertools-opencl-windows-x86-64>run_opencl.bat

C:\minertools-opencl-windows-x86-64>tonlib-opencl-cli.exe -V
tonlib-cli build information: [ Commit: e624a4b82cab7e3a85817caa39e07691bcf4235f, Date: 2021-11-19 11:40:06 +0300]

C:\minertools-opencl-windows-x86-64>tonlib-opencl-cli.exe -v 3 -C global.config.json -e "pminer start kf91o4NNTryJ-Cw3sDGt9OTiafmETdVFUMvylQdFPoOxIsLm EQC_SzjNNdRVvvgry-5KyP8C3xqKn4wlMXU83U_3_g655a3d 0 128 0"
[ 3][t 1][2021-11-21 13:32:43.3165770][TonlibClient.cpp:2108][!Tonlib]  Use blockchain name from MASTER config: 'mainnet' (was '')
[ 2][t 1][2021-11-21 13:32:43.3225119][tonlib-cli.cpp:286][!console]    Tonlib is inited
[ 3][t 1][2021-11-21 13:32:43.3226308][tonlib-cli.cpp:906][!console]    Miner #1 created
[ 2][t 2][2021-11-21 13:32:43.5445211][tonlib-cli.cpp:818][!PowMiner]   pminer: got new options from kf91o4NNTryJ-Cw3sDGt9OTiafmETdVFUMvylQdFPoOxIsLm, seed=215888471240464835851044450636309839839, complexity=44146687380610220277497677693269530213863720751233115016253270
[ 3][t 2][2021-11-21 13:32:43.5447445][tonlib-cli.cpp:823][!PowMiner]   [ expected required hashes for success: 2622894176385554 ]
[ 3][t 2][2021-11-21 13:32:43.5454573][tonlib-cli.cpp:687][!PowMiner]   pminer: start workers
[ OpenCL: set kernel source (17937 bytes) ]
[ OpenCL: platform #0 device #0 NVIDIA GeForce GTX 650 ]
[ OpenCL: create context for platform #0 device #0 NVIDIA GeForce GTX 650, max work group size is 1024 ]
[ 2][t 4][2021-11-21 13:32:43.6086858][sha256.cpp:29]   [ START MINER, GPU ID: 0, boost factor: 128, throughput: 67108864 ]
[ 3][t 2][2021-11-21 13:32:48.5474439][Miner.cpp:105][!PowMiner]        [ mining in progress, passed: 5001.9ms, hashes computed: 67108864, instant speed: 27.099 Mhash/s, average speed: 13.417 Mhash/s ]
[ 3][t 1][2021-11-21 13:32:48.7168850][tonlib-cli.cpp:814][!PowMiner]   mining seed 2158...9839
[ 3][t 2][2021-11-21 13:32:53.7310209][Miner.cpp:105][!PowMiner]        [ mining in progress, passed: 10.2s, hashes computed: 201326592, instant speed: 19.400 Mhash/s, average speed: 19.766 Mhash/s ]
[ 3][t 2][2021-11-21 13:32:53.9452335][tonlib-cli.cpp:814][!PowMiner]   mining seed 2158...9839
[ 3][t 2][2021-11-21 13:32:58.9499905][Miner.cpp:105][!PowMiner]        [ mining in progress, passed: 15.4s, hashes computed: 268435456, instant speed: 19.256 Mhash/s, average speed: 17.426 Mhash/s ]
[ 3][t 2][2021-11-21 13:32:59.1460524][tonlib-cli.cpp:814][!PowMiner]   mining seed 2158...9839
[ 1][t 4][2021-11-21 13:33:03.1662670][opencl.cpp:228]  Error -36 executing clFinish(command_queue_) on D:\a\pow-miner-gpu\pow-miner-gpu\crypto\util\opencl\opencl.cpp:228 (invalid command queue)
[pid 8224] [time 1637501583] Signal: 22

C:\minertools-opencl-windows-x86-64>goto _minerstart`

**Comment by IncognitoBA** [comment]
заметил ещё такую ошибку:
[ 1][t 4][2021-11-21 18:39:03.5029381][opencl.cpp:216]  Error -5 executing clEnqueueWriteBuffer(command_queue_, buffer_cpu_id_, CL_TRUE, 0, sizeof(cl_uint), &cpu_id, 0, NULL, NULL) on D:\a\pow-miner-gpu\pow-miner-gpu\crypto\util\opencl\opencl.cpp:216 (out of resources)

Обновил майнер до 20211121-1, но эти сообщения всё равно появляются.

**Comment by IncognitoBA** [comment]
Обновил майнер до 20211121-2 - ошибка не пропала.
Снова запустил test_cuda.bat и заметил, что ошибка появляется при BOOST_FACTOR =128 и больше.
Установил BOOST_FACTOR = 64.
Работает!

**Comment by DelphiR** [comment]
Да, это особенность старых карт и систем. Я проверял и багу реально словить. Как совет используйте boost factor в диапазоне 16...32
