### ISSUE TITLE
pminer: [Error : 400 : INVALID_ACCOUNT_ADDRESSFailed to parse account address] (#1091931590)

### ISSUE THREAD

**Issue by Lexicon36** [tontechio/pow-miner-gpu#87]
[ mining in progress, passed: 72.9s, hashes computed: 53972303872, instant speed: 745.763 Mhash/s, average speed: 739.937 Mhash/s ]
[ 3][t 1][2021-11-21 18:20:04.9798475][tonlib-cli.cpp:938][!PowMiner]	pminer: got kf8gf1PQy4u2kURl-Gz4LbS29eaN4sVdrVQkPO-JL80VhOe6 complexity=55181218476790784311111488815938817050282010591876540636107044
[ 3][t 1][2021-11-21 18:20:04.9942871][tonlib-cli.cpp:938][!PowMiner]	pminer: got kf91o4NNTryJ-Cw3sDGt9OTiafmETdVFUMvylQdFPoOxIsLm complexity=63286071263483394503174319075673390782513398138833930504247572
[ 3][t 1][2021-11-21 18:20:04.9944045][tonlib-cli.cpp:938][!PowMiner]	pminer: got kf8kO6K6Qh6YM4ddjRYYlvVAK7IgyW8Zet-4ZvNrVsmQ4EOF complexity=59300189305688834954034771260082227499212682164329933766712841
[ 3][t 1][2021-11-21 18:20:09.7566019][tonlib-cli.cpp:921][!PowMiner]	pminer: SELECTED GIVER ():  complexity=0
[ 3][t 1][2021-11-21 18:20:09.7570188][Miner.cpp:105][!PowMiner]	[ mining in progress, passed: 114.6s, hashes computed: 162504114176, instant speed: 754.687 Mhash/s, average speed: 1417.890 Mhash/s ]
[ 3][t 1][2021-11-21 18:20:09.7574134][tonlib-cli.cpp:743][!PowMiner]	pminer: start workers
[ 1][t 1][2021-11-21 18:20:09.7577884][tonlib-cli.cpp:834][!PowMiner]	pminer: [Error : 400 : INVALID_ACCOUNT_ADDRESSFailed to parse account address] (#1091931590)

**Comment by mogadanez** [comment]
same for me

**Comment by Lexicon36** [comment]
I download the latest Software an now it works
