### ISSUE TITLE
How to mine in multi-gpu

### ISSUE THREAD

**Issue by MyProxy** [tontechio/pow-miner-gpu#88]
the `g` parameter just only give 1 gpu id.
I have 8 RTX 3060 so how to mine in all gpu's in same time ?
I tried `-g 0,1,2,3,4,5,6,7` and  `-g 0-7` but doesn't work and just select gpu 0
- using the latest release

**Comment by optimis3232** [comment]
copy all miner files to other folder and try -g 1

**Comment by optimis3232** [comment]
> the `g` parameter just only give 1 gpu id. I have 8 RTX 3060 so how to mine in all gpu's in same time ? I tried `-g 0,1,2,3,4,5,6,7` and `-g 0-7` but doesn't work and just select gpu 0
> 
>     * using the latest release

copy all miner files to another folder and try -g 1

**Comment by optimis3232** [comment]
Open console/terminal 1-2...N times and   change only -g value in arguments -g 0 in fist terminal,-g 1 second terminal, etc..

**Comment by DelphiR** [comment]
Each GPU need is own folder and config with a mainer. There is no way to start the one mainer for several GPUs

**Comment by sc0Vu** [comment]
I think it's related to https://github.com/tontechio/pow-miner-gpu/issues/3. You have to start different miners for each GPU.
