### ISSUE TITLE
pminer: [Error : 500 : LITE_SERVER_NETWORKadnl query timeout(during last block synchronization)] (#221365032)

### ISSUE THREAD

**Issue by Salexber** [tontechio/pow-miner-gpu#91]
An error appears and the miner stops. Releases 20211121-2.

**Comment by Salexber** [comment]
I have automated the launch of the miner. Is this error related to finding a block?

**Comment by DelphiR** [comment]
No. This is warning and not affect the next steps to start the normal work of miner
