### ISSUE TITLE
Why my instant speed always 0? Mhash/s?

### ISSUE THREAD

**Issue by baseoleph** [tontechio/pow-miner-gpu#93]
![image](https://user-images.githubusercontent.com/63150311/143293378-f8c87d04-d384-4907-833f-f3f794fefbd7.png)

How this speed is calculate? Is it real to win for me with zero instant speed?

PS I understand that with my average hashrate I must mine about ten years to get 100 tons.

**Comment by optimis3232** [comment]
1. how u run miner ?
2. whats devices do you use ? 
3. add log file with more info

**Comment by baseoleph** [comment]
/usr/bin/ton_miner/tonlib/tonlib-cli -v 3 -C /usr/bin/ton_miner/global.config.json -e 'pminer start auto [my_addr] 3'

I'm on top of master (b61a1d6a3dac4e33b098c4f2ba18b48fb447b59e)

I use i5-4670 CPU @ 3.40GHz

`[1;36m[ 3][t 1][2021-11-19 20:06:28.997401765][TonlibClient.cpp:2108][!Tonlib]	Use blockchain name from MASTER config: 'mainnet' (was '')[0m
[1;33m[ 2][t 1][2021-11-19 20:06:29.079339271][tonlib-cli.cpp:286][!console]	Tonlib is inited[0m
[1;36m[ 3][t 1][2021-11-19 20:06:29.079423994][tonlib-cli.cpp:906][!console]	Miner #1 created[0m
[1;36m[ 3][t 2][2021-11-19 20:06:29.080587810][Miner.cpp:105][!PowMiner]	[ mining in progress, passed: 71835.4s, hashes computed: 0, instant speed: 0.000 Mhash/s, average speed: 0.000 Mhash/s ][0m
[1;33m[ 2][t 1][2021-11-19 20:06:29.205176269][tonlib-cli.cpp:818][!PowMiner]	pminer: got new options from kf8JfFUEJhhpRW80_jqD7zzQteH6EBHOzxiOhygRhBdt4z2N, seed=78089235366383737359247996374062127643, complexity=65458471072629254600320955543718952367526253107882758129078040[0m
[1;36m[ 3][t 1][2021-11-19 20:06:29.205217095][tonlib-cli.cpp:823][!PowMiner]	[ expected required hashes for success: 1768939716126877 ][0m
[1;36m[ 3][t 1][2021-11-19 20:06:29.205234931][tonlib-cli.cpp:687][!PowMiner]	pminer: start workers[0m
[1;36m[ 3][t 1][2021-11-19 20:06:34.207226348][Miner.cpp:105][!PowMiner]	[ mining in progress, passed: 5002.0ms, hashes computed: 40894464, instant speed: 0.000 Mhash/s, average speed: 8.176 Mhash/s ][0m
[1;36m[ 3][t 1][2021-11-19 20:06:34.329554805][tonlib-cli.cpp:814][!PowMiner]	mining seed 7808...7643[0m
[1;36m[ 3][t 1][2021-11-19 20:06:39.330501816][Miner.cpp:105][!PowMiner]	[ mining in progress, passed: 10.1s, hashes computed: 84934656, instant speed: 0.000 Mhash/s, average speed: 8.388 Mhash/s ][0m
[1;36m[ 3][t 1][2021-11-19 20:06:39.462938191][tonlib-cli.cpp:814][!PowMiner]	mining seed 7808...7643[0m
[1;36m[ 3][t 2][2021-11-19 20:06:44.467235556][Miner.cpp:105][!PowMiner]	[ mining in progress, passed: 15.3s, hashes computed: 129689911, instant speed: 0.000 Mhash/s, average speed: 8.498 Mhash/s ][0m`

and so on

**Comment by optimis3232** [comment]
U need to Use GPU miner.
CPU too slow now.

**Comment by baseoleph** [comment]
I understand it.

I just want to realize why my instant speed is always zero and can I win in about ten years. :)

**Comment by optimis3232** [comment]
you need 6 years for it with  8.6 MH/S
0 per/sec speed its a little bug ( not depend on mining )

**Comment by baseoleph** [comment]
I see thank you
