### ISSUE TITLE
Сид блока, сид уникального майнера

### ISSUE THREAD

**Issue by optimis3232** [tontechio/pow-miner-gpu#94]
[ 2][t 1][2021-11-25 05:02:36.123004597][tonlib-cli.cpp:929][!PowMiner]	pminer: got new options from kf-FV4QTxLl-7Ct3E6MqOtMt-RGXMxi27g4I645lw6MTWraV, seed=227210298917947041612242331227423346968, complexity=45700534310325966151345979463214036389564407143633435885602596
Подскажите ,  seed=227210298917947041612242331227423346968 это ведь сид блока ,а не уникальный сид для майнера.А как формируется случайность для каждого клиента? Другими словами какие уникальные в данные которые мы считаем ( майним ) у кажого экземпляра клиента.
Если ещё понятнее :
В файле credits.cu
td::int64 i = 0;
  for (; i < options.max_iterations;) { 
Мы начинаем от нуля искать sha256 в блоке, если найдем такой sha256 который меньше сложности, то выдаем это найденное рандомное число как ответ серверу. В этом и состоит весь майнинг.
Но если все майнеры начинают от нуля искать , получается что награду получит самый быстрый. ( но это ведь не так )
Помогите разобраться.
2.
Как узнать сколько на данный момент роздано гиверами монеток?
3.
Правильно ли я понимаю, что все данные хранятся на сервере гивера и если с сервером что-либо неприятное происходит( потеря всех данных без бэкапов, чисто теоретически), то наступает катастрофа для всех соответствующих владельцев кошельков?
4.
Майнинг будет продолжаться вечно или пока текущие 10 гиверов производят раздачу? Что в планах.
5.
Влияют ли видеокарты LHR - low hash rate от nvidia ( типа с защитой от майнинга ) на текущий алгоритм майнинга, или нет? Магазины продают видеокарты, а LHR забывают указывать и сдать такую видеокарту потом проблематично.
6.
Укажите на сайте ton.org в разделе майнинга ожидаемое время удвоение сложности сети, это очень полезная информация для новеньких. По моим прогнозам сложность сети удвоится через 10 суток и майнить будет в 2 раза невыгоднее чем сейчас.
7. 
Возможно-ли в Мск купить тон без посредников, с учетом того что торгуется он на биржах сейчас плохо. (знакомые интересуются)
8.
Я последнее время изучаю этот проект(сутками не сплю), потому что вижу перспективу в Ваших проектах(мне нравится идея, код и юзер-френдли интерфейсы), Вы почему то называете это скамом. Своим искренним интересом, тратой своего времени, я невольно оказываю поддержку Вашему проекту. Так и Вы цените моё время, пожалуйста, я не мошенник. Не буду Вам рассказывать как живется инвалидам на мизерную пенсию в России, но объединяет нас с Вами одно дело - это любовь к программированию. 
9.
Опережая Вашу идею поделюсь одной мыслью. Здорово было бы, чтобы клиенты не считали бесполезно sha256, а решали какую-либо сложную математическую проблему ( фитнес-функция ). Таким образом клиенты бы приносили реальную пользу Мировому Сообществу по поиску новых лекарств, материалов и ценных алгоритмов. Я знаю как это сделать.

**Comment by DelphiR** [comment]
1. Да
2. Tonmine.xyz
3. Многократно зарезервированное распределенное хранилище 
4. Осталось около 260 дней до конца 
5. Нет. Не влияют 
6. Там есть график HPS он и определяет прогноз по сложности. Сейчас каждый день сложность растет 
7.  Exmo.me
8. Мне очень нравится мысль. Давайте познакомимся через личку github. 
9. Через 260 дней вполне можно продолжить и выпустит продолжение с пользой

**Comment by optimis3232** [comment]
1. так а где уникальный сид для майнера ? в этом мой вопрос... не вижу в коде ( я без дебагера в листинге кода смотрю и могу тупить ) поэтому спрашиваю
2. там 150 000 в сутки примерно на 10 гиверов, а где точная статистика?
3. Понял. Значит угроза сети может быть распределена между странами и теоретически сеть никто не сможет убить, только если не навалятся толпой сразу во всех странах где есть сервера
4.  А дальше что? ВсЕ? Майнинг кончился? Это акция такая от Компании ? Раздача монеток за майнинг и привлечение внимание к себе?
5. +
6. +  но все равно я настайваю :))    ожидаемое время удвоение ( цифра )  10 суток например. Это проще. Юзер френдли чтоли.
7. +
8. давайте, но я тут новенький и куда кликать для личного чата совсем не знаю, моя телега @romanbarbie

Обращаю так же Ваше внимание на то, что другие прогеры уже выпустили бота который в 2 раза эффективнее данного кода, что меня весьма опечалило.   Данный майнер показывает 400 мегахэшей на gtx 980, а сторонний код 750.86 Mhash/s  1.9 раза фактически.   Друзья, ну так мы "гавнокодим" или мы трухард программисты? Извиняюсь за прямоту.
Вероятно там лучшее использование shared memory и не только это.

**Comment by DelphiR** [comment]
2. Там же
3. Распределена 
4. Да. Это маркетинг а не технология. Он кончится примерно через 290 дней
6. Удвоение происходило и за сутки на прошедшей неделе

**Comment by DelphiR** [comment]
Ton это открытый проект. Дайте ссылку на то, что форкнули и усовершенствовали другие. Я про хешрейт

**Comment by optimis3232** [comment]
> Ton это открытый проект. Дайте ссылку на то, что форкнули и усовершенствовали другие. Я про хешрейт

1
те чуваки не делятся закрытым кодом, но я не думаю что они могут быть сильно полезны..
я думаю что можно значительно сильнее оптимизировать код для гпу, но так как сложность сети быстро растет, то тут время - ключевой ресурс
2
кто эти люди кто на цпу 2 месяца майнил ? мне интересно
сколько они монеток выцеили халявных?
3
как вы относитесь к тому чтобы сделать клон тона и выпустить свою монетку?  тут тоже ключевой момент время
