### ISSUE TITLE
Problem with main principle of mining

### ISSUE THREAD

**Issue by Viacheslav-Kr** [tontechio/pow-miner-gpu#98]
We can see the statistics:
We have one wallet which has 1/3 of earn. This wallet has 475 people as a worker in the pool. (Okay, maybe it is not a pool, but it looks like that, anyway, the main problem is not with the word "pool".)
If we look at the power of that people - it is 19374.69 GH/s
and it is just a ~ 1/6 of all hash rate! So this "pool" should have 1/6 of earning, but it has 1/3!
So something went wrong with the givers or somewhere else, but the big hash rate has more earn than the little one. And it is a reason to create something like pools, and it breaks the main policy - avoiding the pools!

I think it should be fixed immediately.

**Comment by tontechio** [comment]
Totally agree. But hashrate readings isn't too precise and good for hypothesis only.
BTW, miner now improved compatibility with pools (v. 20211130.1) and we'll see other competitors I hope
