### ISSUE TITLE
Noone will win 100 coint with this miner, i am shoked!

### ISSUE THREAD

**Issue by optimis3232** [tontechio/pow-miner-gpu#99]
Its seems like scam, but i have found this error.
I am schoked coz i mine 1 week with this miner.
............
why you do it guys ? its not a joke

Вы бы выставляли бота в релиз после того как проверили он майнет вообще что то или нет.
Это пздц.

cuda_credits.cu

Value i,  should start from RND64 number not from 0

  td::int64 i = 0, hashes_computed = 0;
  td::Timestamp stat_at = td::Timestamp::now(), instant_stat_at = td::Timestamp::now();
  for (; i < options.max_iterations;) {

**Comment by tontechio** [comment]
Miner generates random "rdata" on each run https://github.com/tontechio/pow-miner-gpu/blob/main/crypto/util/MinerCuda.cpp#L36 
After that miner copies "rdata" to the GPU https://github.com/tontechio/pow-miner-gpu/blob/main/crypto/util/cuda/credits.cu#L38 and iterates over it.
The “i” counts the number of iterations in a loop.

**Comment by optimis3232** [comment]
1.
where is start seed for rdata   ?
2.
i am sorry if its not error, but...   why i have hasrate 400 MH per sec,  other miners have 750 MH per sec
, but if i optimizite cuda code, i ll get  1500 MH... 
in russia its called "shit code"
Its why i dont know what think, and where is next problem can be...

**Comment by tontechio** [comment]
Pull requests are open and welcomed
